### ISSUE TITLE
error after entering token in settings.json file

### ISSUE THREAD

**Issue by sharktie** [Walkoud/hap-selfbot-public#3]
/home/sharktie/hap-selfbot-public/node_modules/discord.js-v11-stable/src/client/websocket/packets/handlers/Ready.js:41
        if (!note.length) note = null;
                  ^

TypeError: Cannot read property 'length' of null
    at ReadyHandler.handle (/home/sharktie/hap-selfbot-public/node_modules/discord.js-v11-stable/src/client/websocket/packets/handlers/Ready.js:41:19)
    at WebSocketPacketManager.handle (/home/sharktie/hap-selfbot-public/node_modules/discord.js-v11-stable/src/client/websocket/packets/WebSocketPacketManager.js:108:65)
    at WebSocketConnection.onPacket (/home/sharktie/hap-selfbot-public/node_modules/discord.js-v11-stable/src/client/websocket/WebSocketConnection.js:336:35)
    at WebSocketConnection.onMessage (/home/sharktie/hap-selfbot-public/node_modules/discord.js-v11-stable/src/client/websocket/WebSocketConnection.js:299:17)
    at WebSocket.onMessage (/home/sharktie/hap-selfbot-public/node_modules/ws/lib/event-target.js:120:16)
    at WebSocket.emit (events.js:376:20)
    at Receiver.receiverOnMessage (/home/sharktie/hap-selfbot-public/node_modules/ws/lib/websocket.js:789:20)
    at Receiver.emit (events.js:376:20)
    at Receiver.dataMessage (/home/sharktie/hap-selfbot-public/node_modules/ws/lib/receiver.js:413:14)
    at Receiver.getData (/home/sharktie/hap-selfbot-public/node_modules/ws/lib/receiver.js:352:17)

**Comment by Walkoud** [comment]
reinstall modules : delete node_modules folder and then reinstall with "npm i"

**Comment by sharktie005** [comment]
still the same error...

**Comment by Walkoud** [comment]
go anydesk ?

**Comment by Walkoud** [comment]
Walkoud#1981

**Comment by sharktie005** [comment]
Ok no never mind. I tried using the token of my alt account and that seems to work. I'm guessing there's something wrong with my main accounts token.

**Comment by KuroSenseii** [comment]
same here, deleting the node_module and reinstall but error

**Comment by Walkoud** [comment]
@KuroSenseii Tu racontes quoi, déjà pour commencer apprend à écrire et reviens parler de développement, tu accuses une personne d'un fait illégal alors que tu n'as aucune preuve, je ne vois pas pourquoi je mettrais un token grabber, et si c'était vrai mon compte github serait déjà ban. Mon but ici est de partager mon travail et de rendre mon projet utile au gens.
