### ISSUE TITLE
node index,js then i get this

### ISSUE THREAD

**Issue by thizsam** [Walkoud/hap-selfbot-public#4]
SyntaxError: Unexpected string
    at wrapSafe (internal/modules/cjs/loader.js:984:16)
    at Module._compile (internal/modules/cjs/loader.js:1032:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47

C:\Users\Sam\Desktop\hap-selfbot-public-master>

**Comment by Walkoud** [comment]
fixed, redownload the index.js
